name: russell-rd

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - statsmodels
  - linearmodels
  - jupyterlab
  - ipykernel
  - ruff
  - pre-commit
  - pytest
  - pip
  - pip:
    - rdrobust
    - wrds
